use utoipa::OpenApi;

#[derive(OpenApi)]
/// Aggregated OpenAPI specification for Neon Beat Back.
#[openapi(
    paths(
        crate::routes::health::healthcheck,
        crate::routes::sse::public_stream,
        crate::routes::sse::admin_stream,
        crate::routes::websocket::ws_handler,
        crate::routes::public::get_teams,
        crate::routes::public::get_current_song,
        crate::routes::public::get_game_phase,
        crate::routes::public::get_pairing_status,
        crate::routes::admin::list_games,
        crate::routes::admin::list_playlists,
        crate::routes::admin::create_playlist,
        crate::routes::admin::get_game_by_id,
        crate::routes::admin::load_game,
        crate::routes::admin::create_game,
        crate::routes::admin::create_game_with_playlist,
        crate::routes::admin::start_game,
        crate::routes::admin::pause_game,
        crate::routes::admin::resume_game,
        crate::routes::admin::reveal_song,
        crate::routes::admin::next_song,
        crate::routes::admin::stop_game,
        crate::routes::admin::end_game,
        crate::routes::admin::mark_field_found,
        crate::routes::admin::validate_answer,
        crate::routes::admin::adjust_score,
        crate::routes::admin::create_team,
        crate::routes::admin::update_team,
        crate::routes::admin::delete_team,
        crate::routes::admin::start_pairing,
        crate::routes::admin::abort_pairing,
    ),
    components(
        schemas(
            crate::dto::health::HealthResponse,
            crate::dto::ws::BuzzerInboundMessage,
            crate::dto::ws::BuzzerAck,
            crate::dto::game::CreateGameWithPlaylistRequest,
            crate::dto::game::TeamInput,
            crate::dto::game::PlaylistInput,
            crate::dto::game::SongInput,
            crate::dto::game::TeamSummary,
            crate::dto::game::GameSummary,
            crate::dto::game::PlaylistSummary,
            crate::dto::game::SongSummary,
            crate::dto::game::PointFieldSummary,
            crate::dto::sse::SystemStatus,
            crate::dto::sse::Handshake,
            crate::dto::sse::TeamSummary,
            crate::dto::sse::FieldsFoundEvent,
            crate::dto::sse::AnswerValidationEvent,
            crate::dto::sse::PhaseChangedEvent,
            crate::dto::sse::SongSnapshot,
            crate::dto::sse::PointFieldSnapshot,
            crate::dto::sse::PairingWaitingEvent,
            crate::dto::sse::PairingAssignedEvent,
            crate::dto::sse::PairingRestoredEvent,
            crate::dto::sse::TestBuzzEvent,
            crate::dto::sse::TeamCreatedEvent,
            crate::dto::sse::TeamUpdatedEvent,
            crate::dto::sse::TeamDeletedEvent,
            crate::dto::admin::GameListItem,
            crate::dto::admin::PlaylistListItem,
            crate::dto::admin::CreateGameRequest,
            crate::dto::admin::FieldKind,
            crate::dto::admin::MarkFieldRequest,
            crate::dto::admin::FieldsFoundResponse,
            crate::dto::admin::AnswerValidationRequest,
            crate::dto::admin::ScoreAdjustmentRequest,
            crate::dto::admin::ActionResponse,
            crate::dto::admin::ScoreUpdateResponse,
            crate::dto::admin::StartGameResponse,
            crate::dto::admin::NextSongResponse,
            crate::dto::admin::StopGameResponse,
            crate::dto::admin::CreateTeamRequest,
            crate::dto::admin::UpdateTeamRequest,
            crate::dto::admin::StartPairingRequest,
            crate::dto::phase::VisibleGamePhase,
            crate::dto::public::TeamsResponse,
            crate::dto::public::CurrentSongResponse,
            crate::dto::public::GamePhaseResponse,
            crate::dto::public::PairingStatusResponse,
        )
    ),
    tags(
        (name = "health", description = "Health check endpoints"),
        (name = "sse", description = "Server-sent events streams"),
        (name = "buzzers", description = "WebSocket operations for buzzer devices"),
        (name = "game", description = "Game bootstrap operations"),
        (name = "admin", description = "Administrative controls for running games"),
        (name = "public", description = "Public read-only projections for the current game state"),
    )
)]
pub struct ApiDoc;
